### ISSUE TITLE
Add Default Drop option for upctl firewall option

### ISSUE THREAD

**Issue by nicovs** [UpCloudLtd/upcloud-cli#101]
**Is your feature request related to a problem? Please describe.**
Through CLI, I need to add 2 seperate rules in the FW atm to block all trafic by default

**Describe the solution you'd like**
and option to set the default action from ACCEPT to DROP, as there is an option in the GUI to do this
```bash
upctl server firewall default-action "${SERVERNAME}" DROP
```
**Describe alternatives you've considered**
```bash
upctl server firewall create "${SERVERNAME}" --direction in --action drop --position 1000 --family IPv4 --comment "Drop all IPv4 traffic"
upctl server firewall create "${SERVERNAME}" --direction in --action drop --position 1000 --family IPv6 --comment "Drop all IPv6 traffic"
bash

**Comment by kangasta** [comment]
Hello, and thank you for reporting this issue!

Creating default/catch-all rule is now possible in `v1.5.0` by only specifying `--direction` and `--action` parameters.
