### ISSUE TITLE
ZSH completion

### ISSUE THREAD

**Issue by Davincible** [UpCloudLtd/upcloud-cli#134]

**Comment by kangasta** [comment]
Thank you for reporting this!

We have been planning to update our [cobra](https://github.com/spf13/cobra) dependecy to version `v1.5.0` once that is released and update our completions handling at the same time. This would likely include adding ZSH completions as well (as they are part of the completion command cobra includes by default).

So, hopefully coming soon!

**Comment by kangasta** [comment]
This is now finally available in [v2.5.0](https://github.com/UpCloudLtd/upcloud-cli/releases/tag/v2.5.0)
