### ISSUE TITLE
Disk gets mounted as IDE not VirtIO by default

### ISSUE THREAD

**Issue by Davincible** [UpCloudLtd/upcloud-cli#146]
Creating a server with the CLI (from a template) results in the OS disk being mounted in `IDE` mode instead of `VirtIo` mode. This has big performance impacts. It's also not the default the UpCloud hub uses.

**Comment by kangasta** [comment]
Thanks for opening this issue!

I was able to reproduce this by using custom template. When using the default `--os` value, storage seems to be mounted with `virtio`.
