### ISSUE TITLE
Please add a subcommand to `upctl storage` to wait for a given storage to be online

### ISSUE THREAD

**Issue by nogweii** [UpCloudLtd/upcloud-cli#174]
**Is your feature request related to a problem? Please describe.**
I'm trying to automate the process of uploading a raw Arch Linux disk image (from their [arch-boxes](https://gitlab.archlinux.org/archlinux/arch-boxes) project) and each step needs the storage to be online. I had to write my own loop around that, and would appreciate the CLI providing that power for me.

**Describe the solution you'd like**
An additional subcommand called "wait" or similar that can take a UUID (and/or title?) and will block until the storage resource is in an online state, ready to be used.

**Describe alternatives you've considered**
I have to write a `while` loop in each of my scripts wrapping `upctl`. Not that I have many, though.

**Additional context**
I built some automation around `upctl` to do what I wanted, but it would be nice if that could have been easier. You can see a copy of [my code in this gist](https://gist.github.com/nogweii/0d9afa8246525d21eaf71ad2d12ae955);

Specifically, I'd like to call out the following lines:

https://gist.github.com/nogweii/0d9afa8246525d21eaf71ad2d12ae955#file-upload_to_upcloud-sh-L22-L29

**Comment by kangasta** [comment]
Hi, thanks for the improvement idea!

We currently have similar behavior for server create and stop commands implemented with `--wait` flag, e.g. `upctl server stop --wait $server-name`.

Following the same pattern, we could add `--wait` flag to `upctl storage import` as well. This would work at least in the gist you provided, right?

**Comment by nogweii** [comment]
Yep, along with the same flag being available for `upctl storage templatise` as well. Add the flag to both would satisfy my use case.
