### ISSUE TITLE
upctl server list --show-ip-addresses -o json does not show ip addresses

### ISSUE THREAD

**Issue by nicovs** [UpCloudLtd/upcloud-cli#283]
**Environment (required):**
- OS: MacOS Sonoma / Ubuntu / ArchLinux / ...
- Version 3.2.2

**Describe the bug**
Querying a server list to include the IP addresses does not work when requesting the output in JSON/YAML format.
When requesting it in human readable, the IP's are shown.
This is tested on MacOS (brew install upcloud-cli), Arch Linux (yay -d upcloud-cli), Ubuntu (download .deb package)

**To Reproduce**
1) Working: `upctl server list --show-ip-addresses=public`
2) Not working:
- `upctl server list --show-ip-addresses=public -o json`  
- `upctl server list --show-ip-addresses=public -o yaml`

**Expected behavior**
JSON and YAML output format should show the IP addresses

**Observed behavior**
It should show IP addreses ;)

**Screenshots**
Too much private info to share ;)

**Comment by nicovs** [comment]
I have tested all versions from the releases: https://github.com/UpCloudLtd/upcloud-cli/releases
It's not working since 3.0.0. Last version that works = **2.10.0**

**Comment by kangasta** [comment]
Hello, thank you for the bug report! This was probably broken when we synced the machine readable outputs with our Go SDK JSON types in `v3.0.0`.

We will take a look if this could be added to the machine readable output as well or if there is a good alternative approach. What is your use case for this: are you using this in a script or for exporting the data?

**Comment by nicovs** [comment]
Tnx for the swift response! 👍 

Yeah, i use upctl in Json output in a script to generate my .ssh/config.
I know i can use the API, but I also use the CLI to to add/remove/update firewall rules etc etc...

**Comment by kangasta** [comment]
This will be available soon in the [v3.4.0](https://github.com/UpCloudLtd/upcloud-cli/releases/tag/v3.4.0) release
