### ISSUE TITLE
UpCloud Swagger File

### ISSUE THREAD

**Issue by zikalino** [UpCloudLtd/upcloud-cli#330]
This is more like a question, and probably I am posting it in a wrong repo.

Do you guys have any public OpenAPI definition filers for your APIs? So far I could find only documentation.

**Comment by villevsv-upcloud** [comment]
Hi! We have no public Swagger / OpenAPI definitions available at this moment. It is something we would like to support in the future, and we will take your inquiry into account.

I'll be closing this issue for now. Feel free to reach out if you have further questions.
