### ISSUE TITLE
Getting Started Guide seems to be outdated

### ISSUE THREAD

**Issue by zikalino** [UpCloudLtd/upcloud-cli#331]
I have followed following guide.

https://upcloud.com/resources/tutorials/get-started-upcloud-command-line-interface

It's a minor thing, but guide says: **Click the Add Member button**
It seems that this button was replaced by **Create subaccount** so it may create some friction for first time user perspective.

Also, I am not sure where to send suggestions / issues related to portal or documentation. Is it the right place?

**Comment by kangasta** [comment]
Thank you for reporting the outdated information!

We do not have generic community discussion forum available at the moment, so using GitHub issues of the most related repository, like you have done here, works well for reporting these issues. 👍 You can also contact our support via the chat button in the lower right corner of our Hub if anything in these guides/tutorials is unclear.

**Comment by kangasta** [comment]
The link in the initial message should now redirect to an updated version of the tutorial.
